### ISSUE TITLE
Failed to create conda environment 

### ISSUE THREAD

**Issue by yuchen93** [kpertsch/rlds_dataset_builder#1]
Hi I wasn't able to create conda environment using the xml file provided. I will try to build one from scratch but would be great if this could have worked! Not sure if this is problem specific to our cluster conda setup.

Error message:

Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libpng==1.6.39=h6c40b1e_0
  - libcxx==14.0.6=h9765a3e_0
  - libgfortran==5.0.0=11_3_0_hecd8cb5_28
  - numpy-base==1.23.5=py311h53bf9ac_1
  - libffi==3.4.4=hecd8cb5_0
  - tensorflow-base==2.12.0=eigen_py311hbf87084_0
  - ncurses==6.4=hcec6c5f_0
  - readline==8.2=hca72f7f_0
  - libev==4.33=h9ed2024_1
  - bzip2==1.0.8=h1de35cc_0
  - zlib==1.2.13=h4dc903c_0
  - libgfortran5==11.3.0=h9dfd629_28
  - jpeg==9e=h6c40b1e_1
  - python==3.11.4=h1fd4e5f_0
  - libnghttp2==1.52.0=h1c88b7d_1
  - tbb==2021.8.0=ha357a0b_0
  - mkl==2023.1.0=h59209a4_43558
  - libprotobuf==3.20.3=hfff2838_0
  - hdf5==1.10.6=h10fe05b_1
  - libcurl==8.1.1=ha585b31_1
  - icu==68.1=h23ab428_0
  - c-ares==1.19.0=h6c40b1e_0
  - flatbuffers==2.0.0=h23ab428_0
  - grpc-cpp==1.48.2=h3afe56f_0
  - ca-certificates==2023.05.30=hecd8cb5_0
  - giflib==5.2.1=h6c40b1e_3
  - mkl_random==1.2.2=py311hdb55bb0_1
  - sqlite==3.41.2=h6c40b1e_0
  - mkl_fft==1.3.6=py311hdb55bb0_1
  - intel-openmp==2023.1.0=ha357a0b_43547
  - libssh2==1.10.0=hdb2fb19_2
  - xz==5.4.2=h6c40b1e_0
  - llvm-openmp==14.0.6=h0dcd299_0
  - tk==8.6.12=h5d9f67b_0
  - krb5==1.20.1=hdba6334_1
  - abseil-cpp==20211102.0=he9d5cce_0
  - libedit==3.1.20221030=h6c40b1e_0
  - typing_extensions==4.6.3=py311hecd8cb5_0
  - openssl==1.1.1u=hca72f7f_0
  - re2==2022.04.01=he9d5cce_0
  - snappy==1.1.9=he9d5cce_0

**Comment by kpertsch** [comment]
Hi Yuchen!

I am also seeing this warning, but the environment is still built correctly for me after, ie I think the warning about the pip dependency is **not** why the environment creation is failing.

I'm not able to reproduce the error you're seeing -- I just updated my conda version to 23.5.2 and am running pip 23.1.2, all on Mac.

Could you check whether your conda and pip versions are similar?

**Comment by kpertsch** [comment]
Hi Yuchen!

I dug into this issue a bit deeper and the problem was that conda environment.yml files don't transfer well between MacOS and Ubuntu. I just pushed an `environment_ubuntu.yml` file that should work on Ubuntu -- if you still need to create a conda environment, you can pull the repo and rerun `conda env create -f environment_ubuntu.yml`

Sorry about the troubles!
