### ISSUE TITLE
image resolution

### ISSUE THREAD

**Issue by qbcleo** [kpertsch/rlds_dataset_builder#11]
![img_v3_02cs_f646baf1-b390-4378-9194-70fc7ad1728g](https://github.com/user-attachments/assets/2f016431-1ab4-4cc2-a547-a84f5d8855b6)
I want to keep the resolution of the original dataset (200), I changed it here, will this work, why is the output dataset resolution still 224? thanks!!

**Comment by kpertsch** [comment]
You need to resize the image in the `_parse_example` function before putting it into the dictionary here: https://github.com/kpertsch/rlds_dataset_builder/blob/cff9f536c53518baa744b0f31e66d53ef445d2a1/example_dataset/example_dataset_dataset_builder.py#L112

**Comment by qbcleo** [comment]
> You need to resize the image in the `_parse_example` function before putting it into the dictionary here:
> 
> https://github.com/kpertsch/rlds_dataset_builder/blob/cff9f536c53518baa744b0f31e66d53ef445d2a1/example_dataset/example_dataset_dataset_builder.py#L112

thanks!!!
